service: nuxt-ssr-lambda

useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${env:NODE_ENV}
  region: ${env:NUXT_AWS_REGION}
  lambdaHashingVersion: 20201221
  environment: 
    NODE_ENV: ${env:NODE_ENV}
  apiGateway:
    shouldStartNameWithService: true

functions:
  nuxt:
    handler: handler.nuxt
    events:
      - http: ANY /
      - http: ANY /{proxy+}

plugins:
  - serverless-domain-manager
  - serverless-apigw-binary
  - serverless-offline

package:
  exclude:
    - src/**
    - .nuxt/**
    - package.json
    - package-lock.json
    - .gitignore
    - README.md
    - .env.example
  include:
    - src/static/**
    - .nuxt/dist/**

custom:
  apigwBinary:
    types:
      - '*/*'
  serverless-offline:
    noPrependStageInUrl: true
  customDomain:
    domainName: ${env:DOMAIN}
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
    endpointType: 'regional'
    certificateArn: ${env:CERTIFICATE_ARN}
